# 🛠️ SPRING BOOT APPLICATION PROPERTIES
# 3. The "Translator" (JPA Settings)
# "update" means: If I change my Java code, update the database tables automatically.
spring.jpa.hibernate.ddl-auto=update

# Show me the SQL commands in the console (Great for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ☁️ CLOUD DATABASE CONFIG (Supabase)
# Replace the URL below with the one you copied from Supabase
# ⚠️ IMPORTANT: Replace '[YOUR-PASSWORD]' with the real password you set in Step 1
# 1. The URL (Without user/pass)
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
# 2. The Username (Use the LONG one you found!)
spring.datasource.username=postgres.ykzyggxeekwihxpqxrvc
# 3. The Password (Just your plain text password, NO brackets)
spring.datasource.password=#madhuri_0109
# Hibernate Settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update